services:
  mongodb:
    image: mongo:7.0
    container_name: dropbox-clone-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: dropbox-clone-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
    container_name: dropbox-clone-backend
    depends_on:
      - mongodb
      - minio
    environment:
      SPRING_MONGODB_URI: ${SPRING_MONGODB_URI}
      APP_STORAGE_ENDPOINT: ${APP_STORAGE_ENDPOINT}
      APP_STORAGE_PUBLIC_ENDPOINT: ${APP_STORAGE_PUBLIC_ENDPOINT}
      APP_STORAGE_ACCESS_KEY: ${APP_STORAGE_ACCESS_KEY}
      APP_STORAGE_SECRET_KEY: ${APP_STORAGE_SECRET_KEY}
      APP_STORAGE_BUCKET: ${APP_STORAGE_BUCKET}
      APP_STORAGE_REGION: ${APP_STORAGE_REGION}
      APP_AUTH_JWT_SECRET: ${APP_AUTH_JWT_SECRET}
      APP_AUTH_JWT_TTL: ${APP_AUTH_JWT_TTL}
    ports:
      - "8080:8080"

#  frontend:
#    build:
#      context: ./frontend
#    container_name: dropbox-clone-frontend
#    depends_on:
#      - backend
#    ports:
#      - "5173:80"

volumes:
  mongodb_data:
  minio_data:
