spring.application.name=dropbox-clone-backend
server.port=8080

spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

app.storage.endpoint=${APP_STORAGE_ENDPOINT}
app.storage.public-endpoint=${APP_STORAGE_PUBLIC_ENDPOINT}
app.storage.access-key=${APP_STORAGE_ACCESS_KEY}
app.storage.secret-key=${APP_STORAGE_SECRET_KEY}
app.storage.bucket=${APP_STORAGE_BUCKET}
app.storage.region=${APP_STORAGE_REGION}

app.auth.jwt.secret=${APP_AUTH_JWT_SECRET}
app.auth.jwt.access-token-ttl-seconds=${APP_AUTH_JWT_TTL}
app.auth.jwt.issuer=dropbox-clone-backend

app.auth.refresh.ttl-days=${APP_AUTH_REFRESH_TTL_DAYS}
app.frontend.origin=${APP_FRONTEND_ORIGIN}

management.endpoints.web.exposure.include=health,info

app.sqs.endpoint=${APP_SQS_ENDPOINT}
app.sqs.queue-url=${APP_SQS_QUEUE_URL}
app.sqs.access-key=${APP_SQS_ACCESS_KEY}
app.sqs.secret-key=${APP_SQS_SECRET_KEY}
app.sqs.region=${APP_STORAGE_REGION}
