spring.application.name=dropbox-clone-backend
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/dropbox_clone

app.storage.endpoint=http://localhost:9000
app.storage.access-key=minioadmin
app.storage.secret-key=minioadmin
app.storage.bucket=dropbox-clone
app.storage.region=us-east-1

app.auth.jwt.secret=VGhpcy1pcy1hLWRldmVsb3BtZW50LW9ubHktand0LXNlY3JldC1mb3ItZHJvcGJveC1jbG9uZQ==
app.auth.jwt.access-token-ttl-seconds=3600
app.auth.jwt.issuer=dropbox-clone-backend

management.endpoints.web.exposure.include=health,info
